server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db_reservation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      eventService:
        registerHealthIndicator: true
        slidingWindowSize: 5          # On regarde les 5 derniers appels
        minimumNumberOfCalls: 3       # Il faut au moins 3 appels pour décider
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s   # Si ça plante, on attend 5s avant de retester
        failureRateThreshold: 50      # Si 50% des appels échouent, on coupe le circuit
        eventConsumerBufferSize: 10
